import phone1 from "../../img/products/Iphone1.png";
import phone2 from "../../img/products/Iphone2.png";
import phone3 from "../../img/products/Iphone3.png";
import phone4 from "../../img/products/Iphone4.png";
import sam1 from "../../img/products/Samsung1.png";
import sam2 from "../../img/products/Samsung2.png";
import sam3 from "../../img/products/Samsung3.png";
import sam4 from "../../img/products/Samsung4.png";
export const ListProduct = [
  {
    id: 0,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Phone",
    typeElement: "NewProduct",
    price: `
    13.000.000`,
    image: phone1,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 1,
    name: `Iphone 14`,
    nameCompany: "Apple",
    typeProduct: "Phone",
    typeElement: "NewProduct",
    price: `
    13.000.000`,
    image: phone2,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 2,
    name: `Iphone 15`,
    nameCompany: "Apple",
    typeProduct: "Phone",
    typeElement: "NewProduct",
    price: `
    13.000.000`,
    image: phone3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 3,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Phone",
    typeElement: "NewProduct",
    price: `
    13.000.000`,
    image: phone4,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 4,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Phone",
    typeElement: "NewProduct",
    price: `
    13.000.000`,
    image: sam1,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 5,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Phone",
    typeElement: "NewProduct",
    price: `
    13.000.000`,
    image: sam2,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 6,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "NewProduct",
    price: `
    13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 8,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `
    13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 9,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `
    13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 10,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 11,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 12,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 13,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 14,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 15,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 16,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 17,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
  {
    id: 18,
    name: `Iphone 13`,
    nameCompany: "Apple",
    typeProduct: "Laptop",
    typeElement: "SaleGood",
    percentSale: "30%",
    price: `13.000.000`,
    image: sam3,
    describe: "Sản phẩm rất tuuyeetj .....",
  },
];
